### ISSUE TITLE
Resize operator optimization

### ISSUE THREAD

**Issue by robinvanemden** [semihlab/connx#3]
Firstly, thanks for making the ONNX resize operator available in connx! However, when benchmarking a basic model ONNX model that makes use of this operator, basic linear resizing appears to be more than 50 times slower than the rest of the model combined. So it would really help if there'd be some way to optimize it.

**Comment by semihlab** [comment]
connx don't uses as H/W accelerator. It's makes connx portable but causes performance issue. connx sometimes become the only solution for very limited devices such as some embedded SoCs. I know there are performance issues for many operators. For example, Conv is 100 times slower than ONNX Runtime from MS. I'm planning to re-engineer all the architecture in this year. (If I successfully get fund from Gov.)

**Comment by robinvanemden** [comment]
I understand. And again, thanks for making the code available as open source! I will root for you to receive funding!
